# Generated by Django 3.2.4 on 2021-10-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters')),
                ('date_posted', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(null=True)),
                ('form_link', models.CharField(max_length=200)),
            ],
        ),
    ]
