# Generated by Django 3.2.4 on 2021-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters'),
        ),
    ]
