# Generated by Django 3.2.4 on 2021-10-31 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_event_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
